/*
 * Copyright (c) 2012-2017, RISE SICS AB
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE
 * COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Author: Nicolas Tsiftes <nvt@acm.org>
 */

#include "vm-functions.h"
#include "vm-log.h"

static const vm_procedure_t operators[] = {
  /* Mathematical functions. */
  VM_OPERATOR(add, VM_TYPE_FLAG(VM_TYPE_INTEGER) | VM_TYPE_FLAG(VM_TYPE_RATIONAL),
              VM_PROCEDURE_EVAL_ARGS, 0, -1),
  VM_OPERATOR(subtract, VM_TYPE_FLAG(VM_TYPE_INTEGER) | VM_TYPE_FLAG(VM_TYPE_RATIONAL),
              VM_PROCEDURE_EVAL_ARGS, 1, -1),
  VM_OPERATOR(multiply, VM_TYPE_FLAG(VM_TYPE_INTEGER) | VM_TYPE_FLAG(VM_TYPE_RATIONAL),
              VM_PROCEDURE_EVAL_ARGS, 0, -1),
  VM_OPERATOR(divide, VM_TYPE_FLAG(VM_TYPE_INTEGER) | VM_TYPE_FLAG(VM_TYPE_RATIONAL),
              VM_PROCEDURE_EVAL_ARGS, 1, -1),
  VM_OPERATOR(gcd, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 0, -1),
  VM_OPERATOR(lcm, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 0, -1),
  VM_OPERATOR(numerator,
	      VM_TYPE_FLAG(VM_TYPE_INTEGER) | VM_TYPE_FLAG(VM_TYPE_RATIONAL),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(denominator,
	      VM_TYPE_FLAG(VM_TYPE_INTEGER) | VM_TYPE_FLAG(VM_TYPE_RATIONAL),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(quotient, VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 2, 2),
  VM_OPERATOR(remainder, VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 2, 2),
  VM_OPERATOR(modulo, VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 2, 2),

  VM_OPERATOR(equal, VM_TYPE_FLAG_NUMBER,
	      VM_PROCEDURE_EVAL_ARGS, 0, -1),
  VM_OPERATOR(different, VM_TYPE_FLAG_NUMBER,
	      VM_PROCEDURE_EVAL_ARGS, 0, -1),
  VM_OPERATOR(less_than, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 0, -1),
  VM_OPERATOR(less_than_equal, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 0, -1),
  VM_OPERATOR(greater_than, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 0, -1),
  VM_OPERATOR(greater_than_equal, VM_TYPE_FLAG_ANY,
	      VM_PROCEDURE_EVAL_ARGS, 0, -1),
  VM_OPERATOR(zerop, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 1, 1),

  /* Primitive functions. */
  VM_OPERATOR(bind, VM_TYPE_FLAG_ANY, 0, -1, -1),
  VM_OPERATOR(return, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 0, 1),
  VM_OPERATOR(begin, VM_TYPE_FLAG_ANY, 0, -1, -1),
  VM_OPERATOR(if, VM_TYPE_FLAG_ANY, 0, 2, 3),
  VM_OPERATOR(define, VM_TYPE_FLAG_ANY, 0, 1, 2),
  VM_OPERATOR(set, VM_TYPE_FLAG_ANY, 0, 2, 2),
  VM_OPERATOR(and, VM_TYPE_FLAG_ANY, 0, -1, -1),
  VM_OPERATOR(or, VM_TYPE_FLAG_ANY, 0, -1, -1),
  VM_OPERATOR(apply, VM_TYPE_FLAG_ANY, 0, 2, 2),
  VM_OPERATOR(quote, VM_TYPE_FLAG_ANY, 0, 1, 1),

  VM_OPERATOR(numberp, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(integerp, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(rationalp, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(realp, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(complexp, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(exactp, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(inexactp, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(procedurep, VM_TYPE_FLAG_ANY, 0, 1, 1),
  VM_OPERATOR(booleanp, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(portp, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(not, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(eqp, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, -1, -1),
  VM_OPERATOR(eqvp, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, -1, -1),
  VM_OPERATOR(equalp, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, -1, -1),

  /* System functions. */
  VM_OPERATOR(system_info, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 0, 0),
  VM_OPERATOR(load_program, VM_TYPE_FLAG(VM_TYPE_STRING),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(import, VM_TYPE_FLAG(VM_TYPE_STRING),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(get_devices, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 0, 0),
  VM_OPERATOR(print, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 1, -1),
  VM_OPERATOR(random, VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 0, 1),
  VM_OPERATOR(time, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 0, 0),
  VM_OPERATOR(get_programs, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 0, 0),
  VM_OPERATOR(program_info, VM_TYPE_FLAG(VM_TYPE_STRING),
	      VM_PROCEDURE_EVAL_ARGS, 0, 1),
  VM_OPERATOR(exit, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 0, 1),

  /* List functions. */
  VM_OPERATOR(list, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, -1, -1),
  VM_OPERATOR(cons, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 2, 2),
  VM_OPERATOR(push, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 2, 2),
  VM_OPERATOR(pop, VM_TYPE_FLAG(VM_TYPE_LIST), VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(car, VM_TYPE_FLAG(VM_TYPE_LIST), VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(cdr, VM_TYPE_FLAG(VM_TYPE_LIST), VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(list_ref,
	      VM_TYPE_FLAG(VM_TYPE_LIST) | VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 2, 2),
  VM_OPERATOR(list_tail,
	      VM_TYPE_FLAG(VM_TYPE_LIST) | VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 2, 2),
  VM_OPERATOR(append, VM_TYPE_FLAG(VM_TYPE_LIST),
	      VM_PROCEDURE_EVAL_ARGS, 2, -1),
  VM_OPERATOR(remove, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 2, 2),
  VM_OPERATOR(reverse, VM_TYPE_FLAG(VM_TYPE_LIST),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(length, VM_TYPE_FLAG(VM_TYPE_LIST),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(nullp, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(listp, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(pairp, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(set_car, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 2, 2),
  VM_OPERATOR(set_cdr, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 2, 2),
  VM_OPERATOR(memq, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 2, 2),
  VM_OPERATOR(memv, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 2, 2),
  VM_OPERATOR(member, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 2, 2),
  VM_OPERATOR(assq, VM_TYPE_FLAG_ANY, 0, 2, 2),
  VM_OPERATOR(assv, VM_TYPE_FLAG_ANY, 0, 2, 2),
  VM_OPERATOR(assoc, VM_TYPE_FLAG_ANY, 0, 2, 2),

  /* Higher-order list functions. */
  VM_OPERATOR(map, VM_TYPE_FLAG_ANY, 0, 2, -1),
  VM_OPERATOR(filter, VM_TYPE_FLAG_ANY, 0, 2, -1),
  VM_OPERATOR(for_each, VM_TYPE_FLAG_ANY, 0, 2, -1),
  VM_OPERATOR(reduce, VM_TYPE_FLAG_ANY, 0, 2, -1),
  VM_OPERATOR(count, VM_TYPE_FLAG_ANY, 0, 2, -1),

  /* Character functions. */
  VM_OPERATOR(charp, VM_TYPE_FLAG_ANY,
              VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(char_compare, VM_TYPE_FLAG(VM_TYPE_CHARACTER),
	      VM_PROCEDURE_EVAL_ARGS, 2, 2),
  VM_OPERATOR(char_class, VM_TYPE_FLAG(VM_TYPE_CHARACTER),
             VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(char_to_integer, VM_TYPE_FLAG(VM_TYPE_CHARACTER),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(integer_to_char, VM_TYPE_FLAG(VM_TYPE_INTEGER),
              VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(char_upcase, VM_TYPE_FLAG(VM_TYPE_CHARACTER),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(char_downcase, VM_TYPE_FLAG(VM_TYPE_CHARACTER),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),

  /* String functions. */
  VM_OPERATOR(make_string,
	      VM_TYPE_FLAG(VM_TYPE_INTEGER) | VM_TYPE_FLAG(VM_TYPE_CHARACTER),
	      VM_PROCEDURE_EVAL_ARGS, 1, 2),
  VM_OPERATOR(string,
	      VM_TYPE_FLAG(VM_TYPE_INTEGER) | VM_TYPE_FLAG(VM_TYPE_CHARACTER),
	      VM_PROCEDURE_EVAL_ARGS, 0, -1),
  VM_OPERATOR(stringp, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(string_length,
	      VM_TYPE_FLAG(VM_TYPE_STRING), VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(string_ref,
	      VM_TYPE_FLAG(VM_TYPE_STRING) | VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 2, 2),
  VM_OPERATOR(string_set, VM_TYPE_FLAG(VM_TYPE_STRING) |
                          VM_TYPE_FLAG(VM_TYPE_INTEGER) |
                          VM_TYPE_FLAG(VM_TYPE_CHARACTER),
	      VM_PROCEDURE_EVAL_ARGS, 3, 3),
  VM_OPERATOR(string_to_list,
	      VM_TYPE_FLAG(VM_TYPE_STRING), VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(list_to_string,
	      VM_TYPE_FLAG(VM_TYPE_LIST), VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(vector_to_string, VM_TYPE_FLAG(VM_TYPE_VECTOR),
              VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(string_fill,
	      VM_TYPE_FLAG(VM_TYPE_STRING) | VM_TYPE_FLAG(VM_TYPE_CHARACTER),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(string_compare, VM_TYPE_FLAG(VM_TYPE_STRING),
	      VM_PROCEDURE_EVAL_ARGS, 2, 2),
  VM_OPERATOR(substring,
	      VM_TYPE_FLAG(VM_TYPE_STRING) | VM_TYPE_FLAG(VM_TYPE_INTEGER),
              VM_PROCEDURE_EVAL_ARGS, 3, 3),
  VM_OPERATOR(string_append, VM_TYPE_FLAG(VM_TYPE_STRING),
              VM_PROCEDURE_EVAL_ARGS, 1, -1),
  VM_OPERATOR(string_copy, VM_TYPE_FLAG(VM_TYPE_STRING),
              VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(string_split, VM_TYPE_FLAG(VM_TYPE_STRING),
              VM_PROCEDURE_EVAL_ARGS, 2, 2),
  VM_OPERATOR(number_to_string, VM_TYPE_FLAG(VM_TYPE_INTEGER),
              VM_PROCEDURE_EVAL_ARGS, 1, 2),
  VM_OPERATOR(string_to_number,
	      VM_TYPE_FLAG(VM_TYPE_STRING) | VM_TYPE_FLAG(VM_TYPE_INTEGER),
              VM_PROCEDURE_EVAL_ARGS, 1, 2),

  /* Exception and condition functions. */
  VM_OPERATOR(guard, VM_TYPE_FLAG_ANY, 0, 3, 3),
  VM_OPERATOR(raise, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 1, 1),

  /* Thread functions. */
  VM_OPERATOR(thread_create, VM_TYPE_FLAG(VM_TYPE_FORM),
              VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(thread_fork, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 0, 0),
  VM_OPERATOR(thread_id, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 0, 0),
  VM_OPERATOR(thread_join, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 0, 0),
  VM_OPERATOR(thread_sleep, VM_TYPE_FLAG_NUMBER,
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(thread_specific, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(thread_specific_set, VM_TYPE_FLAG_ANY,
	      VM_PROCEDURE_EVAL_ARGS, 2, 2),
  VM_OPERATOR(thread_terminate, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 0, 0),
  VM_OPERATOR(thread_yield, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 0, 0),
  VM_OPERATOR(thread_stats, VM_TYPE_FLAG_ANY, 0, 0, 0),

  /* Mutex functions. */
  VM_OPERATOR(mutexp, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(make_mutex, VM_TYPE_FLAG(VM_TYPE_STRING),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(mutex_name, VM_TYPE_FLAG(VM_TYPE_EXTERNAL),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(mutex_specific, VM_TYPE_FLAG(VM_TYPE_EXTERNAL),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(mutex_specific_set, VM_TYPE_FLAG_ANY,
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(mutex_state, VM_TYPE_FLAG(VM_TYPE_EXTERNAL),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(mutex_lock, VM_TYPE_FLAG(VM_TYPE_EXTERNAL),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(mutex_unlock, VM_TYPE_FLAG(VM_TYPE_EXTERNAL),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),

  /* Vector functions. */
  VM_OPERATOR(make_vector, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 1, 2),
  VM_OPERATOR(vector, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 1, -1),
  VM_OPERATOR(vectorp, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(bufferp, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(vector_merge, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 2, -1),
  VM_OPERATOR(vector_length, VM_TYPE_FLAG(VM_TYPE_VECTOR),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(vector_ref,
	      VM_TYPE_FLAG(VM_TYPE_VECTOR) | VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 2, 2),
  VM_OPERATOR(vector_set, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 3, 3),
  VM_OPERATOR(vector_to_list, VM_TYPE_FLAG(VM_TYPE_VECTOR),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(list_to_vector, VM_TYPE_FLAG(VM_TYPE_LIST),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(vector_fill, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(make_buffer, VM_TYPE_FLAG(VM_TYPE_INTEGER),
              VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(buffer_append, VM_TYPE_FLAG_ANY, VM_PROCEDURE_EVAL_ARGS, 3, 3),

  /* I/O functions. */
  VM_OPERATOR(input_portp, VM_TYPE_FLAG_ANY,
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(output_portp, VM_TYPE_FLAG_ANY,
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(current_input_port, VM_TYPE_NONE,
	      VM_PROCEDURE_EVAL_ARGS, 0, 0),
  VM_OPERATOR(current_output_port, VM_TYPE_NONE,
	      VM_PROCEDURE_EVAL_ARGS, 0, 0),
  VM_OPERATOR(open_input_file, VM_TYPE_FLAG(VM_TYPE_STRING),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(open_output_file, VM_TYPE_FLAG(VM_TYPE_STRING),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(close_port, VM_TYPE_FLAG(VM_TYPE_PORT),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(close_port, VM_TYPE_FLAG(VM_TYPE_PORT),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(read_char, VM_TYPE_FLAG(VM_TYPE_PORT),
	      VM_PROCEDURE_EVAL_ARGS, 0, 1),
  VM_OPERATOR(read, VM_TYPE_FLAG(VM_TYPE_PORT),
	      VM_PROCEDURE_EVAL_ARGS, 0, 1),
  VM_OPERATOR(peek_char, VM_TYPE_FLAG(VM_TYPE_PORT),
	      VM_PROCEDURE_EVAL_ARGS, 0, 1),
  VM_OPERATOR(eof_objectp, VM_TYPE_FLAG_ANY,
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(char_readyp, VM_TYPE_FLAG(VM_TYPE_PORT),
	      VM_PROCEDURE_EVAL_ARGS, 0, 1),
  VM_OPERATOR(write_char, VM_TYPE_FLAG_ANY,
	      VM_PROCEDURE_EVAL_ARGS, 1, 2),
  VM_OPERATOR(write, VM_TYPE_FLAG_ANY,
	      VM_PROCEDURE_EVAL_ARGS, 1, 2),
  VM_OPERATOR(display, VM_TYPE_FLAG_ANY,
	      VM_PROCEDURE_EVAL_ARGS, 1, 2),
  VM_OPERATOR(with_input_from_file, VM_TYPE_FLAG_ANY,
              VM_PROCEDURE_EVAL_ARGS, 1, 2),
  VM_OPERATOR(with_output_to_file, VM_TYPE_FLAG_ANY,
              VM_PROCEDURE_EVAL_ARGS, 1, 2),
  VM_OPERATOR(make_client, VM_TYPE_FLAG(VM_TYPE_SYMBOL) |
                           VM_TYPE_FLAG(VM_TYPE_STRING) |
                           VM_TYPE_FLAG(VM_TYPE_VECTOR) |
                           VM_TYPE_FLAG(VM_TYPE_INTEGER),
              VM_PROCEDURE_EVAL_ARGS, 3, 4),
  VM_OPERATOR(make_server, VM_TYPE_FLAG(VM_TYPE_SYMBOL) |
                           VM_TYPE_FLAG(VM_TYPE_VECTOR) |
                           VM_TYPE_FLAG(VM_TYPE_INTEGER),
              VM_PROCEDURE_EVAL_ARGS, 3, 3),
  VM_OPERATOR(peer_name, VM_TYPE_FLAG(VM_TYPE_PORT),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(accept_client, VM_TYPE_FLAG(VM_TYPE_PORT),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(incoming_clientp, VM_TYPE_FLAG(VM_TYPE_PORT),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(addr_to_string, VM_TYPE_FLAG(VM_TYPE_VECTOR),
              VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(resolve_hostname, VM_TYPE_FLAG(VM_TYPE_STRING),
              VM_PROCEDURE_EVAL_ARGS, 1, 1),

  /* Mathematical functions using floats. */
  VM_OPERATOR(floor, VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(ceiling, VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(round, VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(truncate, VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(exp, VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(log, VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(sin, VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(cos, VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(tan, VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(asin, VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(acos, VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(atan, VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(sqrt, VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(expt, VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(exact_to_inexact, VM_TYPE_FLAG_NUMBER,
              VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(inexact_to_exact, VM_TYPE_FLAG_NUMBER,
              VM_PROCEDURE_EVAL_ARGS, 1, 1),

  /* Evaluation control functions. */
  VM_OPERATOR(call_with_cc, VM_TYPE_FLAG_ANY, 0, 0, 0),
  VM_OPERATOR(values, VM_TYPE_FLAG_ANY, 0, 0, 0),
  VM_OPERATOR(call_with_values, VM_TYPE_FLAG_ANY, 0, 0, 0),
  VM_OPERATOR(dynamic_wind, VM_TYPE_FLAG_ANY, 0, 3, 3),
  VM_OPERATOR(eval, VM_TYPE_FLAG_ANY, 0, 0, 0),

  /* Bit manipulation functions. */
  VM_OPERATOR(bit_and, VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 2, 2),
  VM_OPERATOR(bit_or, VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 2, 2),
  VM_OPERATOR(bit_invert, VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(bit_not, VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 1, 1),
  VM_OPERATOR(bit_xor, VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 2, 2),
  VM_OPERATOR(bit_shift, VM_TYPE_FLAG(VM_TYPE_INTEGER),
	      VM_PROCEDURE_EVAL_ARGS, 2, 2),

  /* Packet management functions. */
  VM_OPERATOR(construct_packet, VM_TYPE_FLAG(VM_TYPE_VECTOR),
              VM_PROCEDURE_EVAL_ARGS, 2, 2),
  VM_OPERATOR(deconstruct_packet, VM_TYPE_FLAG(VM_TYPE_VECTOR),
              VM_PROCEDURE_EVAL_ARGS, 2, 2),
};

#define MAX_COMMON_SYMBOL_ID 127
#define MAX_LOCAL_SYMBOL_ID 255

unsigned
vm_procedure_count(void)
{
  return ARRAY_SIZE(operators);
}

const vm_procedure_t *
vm_procedure_lookup(vm_program_t *program, vm_symbol_ref_t *symbol_ref)
{
  static vm_procedure_t lambda_proc =
    {
      .operator = NULL,
      .expr_id = 0,
      .valid_types =  VM_TYPE_FLAG_ANY,
      .min_args = -1,
      .max_args = -1,
      .flags = 0
    };
  vm_obj_t *obj;

  if(symbol_ref->scope == VM_SYMBOL_SCOPE_CORE) {
    if(symbol_ref->symbol_id >= ARRAY_SIZE(operators)) {
      return NULL;
    }
    /* The symbol refers to a core function. */
    return &operators[symbol_ref->symbol_id];
  }

  if(symbol_ref->scope == VM_SYMBOL_SCOPE_APP &&
     symbol_ref->symbol_id > MAX_LOCAL_SYMBOL_ID) {
    return NULL;
  }

  /* Check the program's locally created operators. */
  if(symbol_ref->symbol_id >= VM_TABLE_SIZE(program->symbols)) {
    VM_DEBUG(VM_DEBUG_LOW, "Symbol ID too high; max is %d",
            (int)(VM_TABLE_SIZE(program->symbols) - 1));
    return NULL;
  }

  obj = &program->symbol_bindings[symbol_ref->symbol_id];
  if(obj->type == VM_TYPE_PROCEDURE) {
    /* The symbol is bound to a library procedure. */
    return obj->value.procedure;
  } else if(obj->type != VM_TYPE_FORM) {
    /* At this point, we can only accept lambda forms. */
    return NULL;
  }

  lambda_proc.expr_id = obj->value.form.id;
  return &lambda_proc;
}
